export type TacticalMomentumWatchItem = {
  symbol: string;
  name: string;
  group: string;
};

export const TACTICAL_MOMENTUM_WATCHLIST: TacticalMomentumWatchItem[] = [
  { symbol: "NVDA", name: "NVIDIA", group: "Semis & AI" },
  { symbol: "AVGO", name: "Broadcom", group: "Semis & AI" },
  { symbol: "AMD", name: "Advanced Micro Devices", group: "Semis & AI" },
  { symbol: "ARM", name: "Arm Holdings", group: "Semis & AI" },
  { symbol: "MU", name: "Micron", group: "Semis & AI" },
  { symbol: "LRCX", name: "Lam Research", group: "Semis & AI" },
  { symbol: "KLAC", name: "KLA", group: "Semis & AI" },
  { symbol: "AMAT", name: "Applied Materials", group: "Semis & AI" },
  { symbol: "ASML", name: "ASML", group: "Semis & AI" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", group: "Semis & AI" },
  { symbol: "SMCI", name: "Super Micro Computer", group: "AI Hardware & Infra" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", group: "AI Hardware & Infra" },
  { symbol: "DELL", name: "Dell Technologies", group: "AI Hardware & Infra" },
  { symbol: "ANET", name: "Arista Networks", group: "AI Hardware & Infra" },
  { symbol: "VRT", name: "Vertiv", group: "AI Hardware & Infra" },
  { symbol: "MRVL", name: "Marvell Technology", group: "AI Hardware & Infra" },
  { symbol: "META", name: "Meta Platforms", group: "Selective Mega Cap" },
  { symbol: "AMZN", name: "Amazon", group: "Selective Mega Cap" },
  { symbol: "GOOGL", name: "Alphabet Class A", group: "Selective Mega Cap" },
  { symbol: "GOOG", name: "Alphabet Class C", group: "Selective Mega Cap" },
  { symbol: "QQQ", name: "Invesco QQQ", group: "ETF Anchors" },
  { symbol: "XLE", name: "Energy Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "XLB", name: "Materials Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "GE", name: "GE Aerospace", group: "Cyclicals & Industrials" },
  { symbol: "CAT", name: "Caterpillar", group: "Cyclicals & Industrials" },
  { symbol: "DE", name: "Deere", group: "Cyclicals & Industrials" },
  { symbol: "ETN", name: "Eaton", group: "Cyclicals & Industrials" },
  { symbol: "PH", name: "Parker-Hannifin", group: "Cyclicals & Industrials" },
  { symbol: "URI", name: "United Rentals", group: "Cyclicals & Industrials" },
  { symbol: "JBL", name: "Jabil", group: "Cyclicals & Industrials" },
  { symbol: "RTX", name: "RTX", group: "Cyclicals & Industrials" },
  { symbol: "LMT", name: "Lockheed Martin", group: "Cyclicals & Industrials" },
  { symbol: "XOM", name: "Exxon Mobil", group: "Energy & Services" },
  { symbol: "CVX", name: "Chevron", group: "Energy & Services" },
  { symbol: "COP", name: "ConocoPhillips", group: "Energy & Services" },
  { symbol: "SLB", name: "SLB", group: "Energy & Services" },
  { symbol: "HAL", name: "Halliburton", group: "Energy & Services" },
  { symbol: "EQT", name: "EQT", group: "Energy & Services" },
  { symbol: "FCX", name: "Freeport-McMoRan", group: "Materials & Metals" },
  { symbol: "NEM", name: "Newmont", group: "Materials & Metals" },
  { symbol: "LIN", name: "Linde", group: "Materials & Metals" },
  { symbol: "MOS", name: "Mosaic", group: "Materials & Metals" },
  { symbol: "NUE", name: "Nucor", group: "Materials & Metals" },
  { symbol: "MLM", name: "Martin Marietta Materials", group: "Materials & Metals" },
  { symbol: "JPM", name: "JPMorgan Chase", group: "Financial Momentum" },
  { symbol: "GS", name: "Goldman Sachs", group: "Financial Momentum" },
  { symbol: "BAC", name: "Bank of America", group: "Financial Momentum" },
  { symbol: "KKR", name: "KKR", group: "Financial Momentum" },
  { symbol: "IBKR", name: "Interactive Brokers", group: "Financial Momentum" },
  { symbol: "XLF", name: "Financial Select Sector SPDR", group: "ETF Anchors" },
];
