export type TacticalMomentumWatchItem = {
  symbol: string;
  name: string;
  group: string;
};

export const TACTICAL_MOMENTUM_WATCHLIST: TacticalMomentumWatchItem[] = [
  { symbol: "NVDA", name: "NVIDIA", group: "Semis & AI" },
  { symbol: "AVGO", name: "Broadcom", group: "Semis & AI" },
  { symbol: "AMD", name: "Advanced Micro Devices", group: "Semis & AI" },
  { symbol: "ARM", name: "Arm Holdings", group: "Semis & AI" },
  { symbol: "MU", name: "Micron", group: "Semis & AI" },
  { symbol: "LRCX", name: "Lam Research", group: "Semis & AI" },
  { symbol: "ASML", name: "ASML", group: "Semis & AI" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", group: "Semis & AI" },
  { symbol: "META", name: "Meta Platforms", group: "Platform Leaders" },
  { symbol: "AMZN", name: "Amazon", group: "Platform Leaders" },
  { symbol: "NFLX", name: "Netflix", group: "Platform Leaders" },
  { symbol: "TSLA", name: "Tesla", group: "Platform Leaders" },
  { symbol: "UBER", name: "Uber", group: "Platform Leaders" },
  { symbol: "PLTR", name: "Palantir", group: "Platform Leaders" },
  { symbol: "HOOD", name: "Robinhood", group: "Platform Leaders" },
  { symbol: "QQQ", name: "Invesco QQQ", group: "ETF Anchors" },
  { symbol: "XLK", name: "Technology Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "IGV", name: "iShares Expanded Tech-Software ETF", group: "ETF Anchors" },
  { symbol: "ANET", name: "Arista Networks", group: "Software & Infra" },
  { symbol: "NOW", name: "ServiceNow", group: "Software & Infra" },
  { symbol: "CRWD", name: "CrowdStrike", group: "Software & Infra" },
  { symbol: "PANW", name: "Palo Alto Networks", group: "Software & Infra" },
  { symbol: "NET", name: "Cloudflare", group: "Software & Infra" },
  { symbol: "DDOG", name: "Datadog", group: "Software & Infra" },
  { symbol: "SNOW", name: "Snowflake", group: "Software & Infra" },
  { symbol: "APP", name: "AppLovin", group: "Software & Infra" },
  { symbol: "DUOL", name: "Duolingo", group: "Software & Infra" },
  { symbol: "SHOP", name: "Shopify", group: "Software & Infra" },
  { symbol: "MSFT", name: "Microsoft", group: "Software & Infra" },
  { symbol: "AAPL", name: "Apple", group: "Software & Infra" },
  { symbol: "GE", name: "GE Aerospace", group: "Cyclicals & Industrials" },
  { symbol: "CAT", name: "Caterpillar", group: "Cyclicals & Industrials" },
  { symbol: "ETN", name: "Eaton", group: "Cyclicals & Industrials" },
  { symbol: "PH", name: "Parker-Hannifin", group: "Cyclicals & Industrials" },
  { symbol: "URI", name: "United Rentals", group: "Cyclicals & Industrials" },
  { symbol: "JBL", name: "Jabil", group: "Cyclicals & Industrials" },
  { symbol: "FSLR", name: "First Solar", group: "Cyclicals & Industrials" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "JPM", name: "JPMorgan Chase", group: "Financial Momentum" },
  { symbol: "GS", name: "Goldman Sachs", group: "Financial Momentum" },
  { symbol: "MS", name: "Morgan Stanley", group: "Financial Momentum" },
  { symbol: "BAC", name: "Bank of America", group: "Financial Momentum" },
  { symbol: "KKR", name: "KKR", group: "Financial Momentum" },
  { symbol: "IBKR", name: "Interactive Brokers", group: "Financial Momentum" },
  { symbol: "XLF", name: "Financial Select Sector SPDR", group: "ETF Anchors" },
  { symbol: "GOOGL", name: "Alphabet Class A", group: "Platform Leaders" },
  { symbol: "GOOG", name: "Alphabet Class C", group: "Platform Leaders" },
  { symbol: "ORCL", name: "Oracle", group: "Software & Infra" },
  { symbol: "CRSP", name: "CRISPR Therapeutics", group: "Biotech & Special Situations" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF", group: "ETF Anchors" },
];
