create table if not exists public.daily_symbol_facts (
  id bigint generated by default as identity primary key,
  date date not null,
  symbol text not null,
  close numeric,
  sma20 numeric,
  sma50 numeric,
  sma200 numeric,
  above_sma20 boolean,
  above_sma50 boolean,
  above_sma200 boolean,
  atr14 numeric,
  atr_ratio numeric,
  avg_volume20 numeric,
  avg_dollar_volume20 numeric,
  relative_volume numeric,
  high_30bar numeric,
  low_30bar numeric,
  drop_from_30bar_high_pct numeric,
  distance_from_sma20_pct numeric,
  distance_from_sma50_pct numeric,
  distance_from_sma200_pct numeric,
  trend_state text,
  extension_state text,
  liquidity_state text,
  volatility_state text,
  source text default 'scan_pipeline',
  updated_at timestamptz default now()
);

create unique index if not exists uq_daily_symbol_facts_date_symbol
  on public.daily_symbol_facts (date, symbol);

create index if not exists idx_daily_symbol_facts_symbol_date
  on public.daily_symbol_facts (symbol, date desc);

create index if not exists idx_daily_symbol_facts_date
  on public.daily_symbol_facts (date desc);
